### ISSUE TITLE
Remote computer refused the network connection

### ISSUE THREAD

**Issue by jellydreams** [jellydreams/VTS-Fullbody-Tracking#6]
When selecting the camera and hitting "start tracking", this message appears:

```
Traceback (most recent call last):
  File "app.py", line 188, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "app.py", line 46, in main
  File "pyvts\vts.py", line 77, in connect
  File "websockets\legacy\client.py", line 647, in __await_impl_timeout__
  File "websockets\legacy\client.py", line 651, in __await_impl__
  File "asyncio\base_events.py", line 1090, in create_connection
  File "asyncio\base_events.py", line 1069, in create_connection
  File "asyncio\base_events.py", line 973, in _connect_sock
  File "asyncio\proactor_events.py", line 726, in sock_connect
  File "asyncio\windows_events.py", line 846, in _poll
  File "asyncio\windows_events.py", line 633, in finish_connect
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection
```

**Comment by jellydreams** [comment]
To resolve this issue:
 - Vtube Studio should be running.
 - The Start API toggle should be turned on.
 - The plugin port must be the same as the Vtube Studio API (default 8001)
![image](https://github.com/jellydreams/VTS-Fullbody-Tracking/assets/151779294/5e9ff43b-32c6-4e0c-92d0-ae3374470b2c)
