### ISSUE TITLE
ConnectionClosedError: no close frame received or sent

### ISSUE THREAD

**Issue by jellydreams** [jellydreams/VTS-Fullbody-Tracking#7]
After allowing the plugin in Vtube Studio, the camera window shows up and this error occurs:

```
Traceback (most recent call last):
  File "websockets\legacy\protocol.py", line 963, in transfer_data
  File "websockets\legacy\protocol.py", line 1033, in read_message
  File "websockets\legacy\protocol.py", line 1108, in read_data_frame
  File "websockets\legacy\protocol.py", line 1165, in read_frame
  File "websockets\legacy\framing.py", line 98, in read
  File "asyncio\streams.py", line 736, in readexactly
  File "asyncio\proactor_events.py", line 305, in _loop_reading
  File "asyncio\windows_events.py", line 486, in recv_into
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 176, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "app.py", line 114, in main
  File "pyvts\vts.py", line 113, in request
  File "websockets\legacy\protocol.py", line 568, in recv
  File "websockets\legacy\protocol.py", line 939, in ensure_open
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by jellydreams** [comment]
Resources Potential Fixes (for developers):
- Documentation Websocket - [What does ConnectionClosedError: no close frame received or sent mean?](https://websockets.readthedocs.io/en/stable/faq/common.html)

**Comment by jellydreams** [comment]
Added parameter `ping_interval=None` in the pyvts.connect() method in the pyvts library

If you have this issue, you can download [v0.1.3 (fix)](https://github.com/jellydreams/VTS-Fullbody-Tracking/releases/tag/v0.1.3_fix) and let me know if it works for you
